### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by RealyUniqueName** [luboslenco/lue#4]
Hello. I'm following this guide: https://github.com/luboslenco/fox/wiki
But on the last step i get these errors in terminal (started blender from command line):
```
PyContext 'window' not found
PyContext 'window' not found
Generating Kha project.
Exporting asset 1 of 2 (data.json).

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'Assets/data.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.exports.copy (/home/alex/temp/foxtest/Kha/Kore/Tools/koremake/Files.js:31:71)
    at Exporter.KhaExporter.copyFile (/home/alex/temp/foxtest/Kha/Tools/khamake/KhaExporter.js:22:8)
    at Exporter.Html5Exporter.copyBlob (/home/alex/temp/foxtest/Kha/Tools/khamake/Html5Exporter.js:134:7)
    at exportAssets (/home/alex/temp/foxtest/Kha/Tools/khamake/main.js:184:12)
    at exportKhaProject (/home/alex/temp/foxtest/Kha/Tools/khamake/main.js:263:3)
    at exportProject (/home/alex/temp/foxtest/Kha/Tools/khamake/main.js:439:3)
    at Object.exports.run (/home/alex/temp/foxtest/Kha/Tools/khamake/main.js:514:2)
    at Object.<anonymous> (/home/alex/temp/foxtest/Kha/Tools/khamake/khamake.js:107:22)
```
This is due to case-sensitive filesystem. After fixing assets folder name i advanced to these errors:
```
PyContext 'window' not found
PyContext 'window' not found
Generating Kha project.
Exporting asset 1 of 2 (data.json).
Exporting asset 2 of 2 (Scene.ogex).
Assets done.
kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
Haxe stderr: Class not found : Main

Haxe process exited with code 1
Done.
```
Which i don't know how to workaround since kfx-linux seems to be binary file.
Any ideas?

Also on Linux `node` is located at `/usr/bin/nodejs` or `/usr/bin/node`, not in `/usr/locale/bin/node` :)

**Comment by luboslenco** [comment]
Hello Alexander,

Thanks for taking your time to report those.

Made some adjustments in Blender plugins, there is an updated test.blend file [here](https://github.com/luboslenco/fox_project).

'Assets', 'Sources' and 'Shaders' folders are now upper case, also tried to fix wrong node lookup. Please let me know if you got it to work. :)

Lubos

**Comment by RealyUniqueName** [comment]
Hey, i tried it and those issues are resolved now.
But i still can't finish building test project :)

If i try to build for linux i get CodeBlocks project which fails to compile due to various c++ related errors (like invalid casts, undeclared sprintf etc.) I have no experience in C++, so i can't fix them.

If i try to builf for HTML5, i get this:
```
PyContext 'window' not found
PyContext 'window' not found
Generating Kha project.
Exporting asset 1 of 2 (data.json).
Exporting asset 2 of 2 (Scene.ogex).
Assets done.
kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
kfx process exited with code 2
Haxe stderr: /home/alex/temp/foxtest/Kha/Tools/haxe/std/js/RegExp.hx:42: lines 42-45 : Cannot extend basic class
/home/alex/temp/foxtest/Kha/Tools/haxe/std/haxe/Http.hx:50: lines 50-832 : Defined in this class
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:39: characters 42-52 : js.RegExpMatch has no field length
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:39: characters 55-58 : Array access is not allowed on js.RegExpMatch
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:38: lines 38-40 : Missing return String
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:44: characters 22-31 : js.RegExpMatch has no field index
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:49: characters 11-20 : js.RegExpMatch has no field index
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:49: characters 21-24 : Array access is not allowed on js.RegExpMatch
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:50: characters 9-37 : Float should be Int
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:50: characters 9-37 : For optional function argument 'len'
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:47: lines 47-51 : Missing return String
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:55: characters 17-26 : js.RegExpMatch has no field index
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:55: characters 34-37 : Array access is not allowed on js.RegExpMatch
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:53: lines 53-56 : Missing return { pos : Int, len : Int }
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:72: characters 4-13 : js.RegExpMatch has no field index
/home/alex/temp/foxtest/Kha/Tools/haxe/std/js/_std/EReg.hx:72: characters 4-13 : js.RegExpMatch has no field index

Haxe process exited with code 1
Done.
```

**Comment by luboslenco** [comment]
Talked to Robert and he did some fixes for Linux, if you get a spare moment please try again from scratch and it should hopefully work.

If not, is there a 'Sources/Shaders' directory?

Thanks,
Lubos

**Comment by RealyUniqueName** [comment]
I tried again and got following results:

For html5:
```
PyContext 'window' not found
PyContext 'window' not found
Generating Kha project.
Exporting asset 1 of 2 (data.json).
Exporting asset 2 of 2 (Scene.ogex).
Assets done.
kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected
<...a lot of copies of string above...>
kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx process exited with code 2
<...a lot of copies of string above...>
kfx process exited with code 2
Haxe stderr: /home/alex/temp/foxtest/Kha/Tools/haxe/haxe-linux: 3: /home/alex/temp/foxtest/Kha/Tools/haxe/haxe-linux: Syntax error: Unterminated quoted string

Haxe process exited with code 2
Done.
```
and `kha.js` is not generated in `build/html5` directory.

For linux:
```
PyContext 'window' not found
PyContext 'window' not found
Generating Kha project.
Exporting asset 1 of 2 (data.json).
Exporting asset 2 of 2 (Scene.ogex).
Assets done.
kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected
<...a lot of copies of string above...>
kfx stderr: Kha/Kore/Tools/kfx/kfx-linux: 1: Kha/Kore/Tools/kfx/kfx-linux: Syntax error: "(" unexpected

kfx process exited with code 2
<...a lot of copies of string above...>
kfx process exited with code 2
Haxe stderr: /home/alex/temp/foxtest/Kha/Tools/haxe/haxe-linux: 3: /home/alex/temp/foxtest/Kha/Tools/haxe/haxe-linux: 
Haxe stderr: Syntax error: Unterminated quoted string
Haxe stderr: 

Haxe process exited with code 2
korefile found, generating build files.
Generating Linux solution
.
.
.
.done.
Done.
```
Despite it says linux solution is generated, `build/linux-build` directory does not contain any source files. Only Code::Blocks project file.

`Sources/Shaders` exists.

**Comment by luboslenco** [comment]
Installed Ubuntu and got it to work. I think it's not working for you because the .blend file needs to be placed in the folder with the same name, eg. 'test/test.blend'. Which is of course a stupid requirement. Added a note to 'Getting Started' section and will fix eventually fix this.

Also it seemed that node can be accessed using 'nodejs' on Linux, hope that works universally.

**Comment by RealyUniqueName** [comment]
I tried from scratch on another machine. And now `fox_build` section in right panel even does not appear :)
I only see `fox_relations` and `fox_traits`
Ubuntu 14.04 x64t, blender 2.73

**Comment by luboslenco** [comment]
You probably used newest compiled.py(?) from fox_blender repo, which I just fixed. But if not then I am out of clues, test.blend should have worked.

Thanks,
Lubos

**Comment by RealyUniqueName** [comment]
On the old machine (where fox_build is available) still no progress. 
I don't know if i use  newest compiled.py. I just oppen test.blend and `Fetch & Run`.
I guess the problem is in this error:
```
Haxe stderr: /home/alex/temp/foxtest/test/Kha/Tools/haxe/haxe-linux: 3: /home/alex/temp/foxtest/test/Kha/Tools/haxe/haxe-linux: Syntax error: Unterminated quoted string
```

**Comment by luboslenco** [comment]
Dang I just booted up Ubuntu 14.04 64bit, Blender 2.73, selected HTML5 target hit 'Run' and done.

What's your distro on old machine? Is it 64bit?

**Comment by RealyUniqueName** [comment]
Ubuntu 14.04 32bit. Blender 2.73

**Comment by luboslenco** [comment]
Robert added binaries for 32bit Linux, you need the most recent Kha. Fingers crossed:)

**Comment by RealyUniqueName** [comment]
Html5 finally compiled! Thanks for your patience :)

But linux build stil fails. Code::blocks project file & c++ source are generated, but compilation fails with errors:
```
/home/alex/temp/foxtest/test/Kha/KoreVideo/libtheoraplayer/src/TheoraDataSource.cpp|75|error: conversion from ‘uint64_t {aka long long unsigned int}’ to non-scalar type ‘fpos_t {aka _G_fpos_t}’ requested|
/home/alex/temp/foxtest/test/Kha/KoreVideo/libtheoraplayer/src/TheoraDataSource.cpp||In member function ‘virtual uint64_t TheoraFileDataSource::tell()’:|
/home/alex/temp/foxtest/test/Kha/KoreVideo/libtheoraplayer/src/TheoraDataSource.cpp|96|error: invalid cast from type ‘fpos_t {aka _G_fpos_t}’ to type ‘uint64_t {aka long long unsigned int}’|
```

**Comment by luboslenco** [comment]
Wohoo, same thanks to you!

Hm seems like it's again related to non-64bit system..

**Comment by RealyUniqueName** [comment]
On 64bit c++ generated code gave me the same errors.

**Comment by luboslenco** [comment]
Should be fixed now! I also changed a few things in fox, hope I didn't break anything - 'Fetch' and 'Build' will no longer freeze Blender and 'Run' button now works with HTML5 target too.

**Comment by RealyUniqueName** [comment]
Everything works much better now for HTML5, but compiling generated linux project still fails with c++ errors :)

**Comment by luboslenco** [comment]
Spring cleaning - Kha should now compile more reliably on Linux too.
